openapi: 3.1.0
info:
  title: Google Docs API
  description: OpenAPI specification for creating, updating, and retrieving Google Docs documents.
  version: "1.0"
servers:
  - url: "https://docs.googleapis.com/v1/documents"
paths:
  /:
    post:
      summary: Create a new document
      operationId: createDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDocumentRequest"
      responses:
        "200":
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "400":
          description: Invalid request
  /{documentId}:
    get:
      summary: Retrieve a document
      operationId: getDocument
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the document to retrieve.
      responses:
        "200":
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "400":
          description: Invalid request
  /{documentId}:batchUpdate:
    post:
      summary: Batch update a document
      operationId: batchUpdateDocument
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the document to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchUpdateDocumentRequest"
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchUpdateDocumentResponse"
        "400":
          description: Invalid request
components:
  schemas:
    CreateDocumentRequest:
      type: object
      properties:
        title:
          type: string
          description: The title of the new document.
    Document:
      type: object
      properties:
        documentId:
          type: string
        title:
          type: string
        body:
          type: object
          properties:
            content:
              type: array
              items:
                type: object
                properties:
                  startIndex:
                    type: integer
                  endIndex:
                    type: integer
                  textRun:
                    type: object
                    properties:
                      content:
                        type: string
                      textStyle:
                        type: object
    BatchUpdateDocumentRequest:
      type: object
      properties:
        requests:
          type: array
          items:
            type: object
            properties:
              insertText:
                type: object
                properties:
                  location:
                    type: object
                    properties:
                      index:
                        type: integer
                    required:
                      - index
                  text:
                    type: string
                    required:
                      - text
              deleteContentRange:
                type: object
                properties:
                  range:
                    type: object
                    properties:
                      startIndex:
                        type: integer
                      endIndex:
                        type: integer
                    required:
                      - startIndex
                      - endIndex
    BatchUpdateDocumentResponse:
      type: object
      properties:
        documentId:
          type: string
        replies:
          type: array
          items:
            type: object
