openapi: 3.1.0
info:
  title: Google Sheets API Operations
  description: An OpenAPI specification for reading and appending a range of cells in a Google Sheet.
  version: "1.0"
servers:
  - url: https://sheets.googleapis.com/v4/spreadsheets

paths:
  /{spreadsheetId}:
    get:
      summary: Read the entire spreadsheet
      operationId: getSpreadsheetValuesEntire
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the spreadsheet to retrieve data from.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueRange"
        "400":
          description: Bad Request

  /{spreadsheetId}/values/{range}:
    get:
      summary: Read a range of values in a spreadsheet
      operationId: getSpreadsheetValuesRange
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the spreadsheet to retrieve data from.
        - name: range
          in: path
          required: true
          schema:
            type: string
          description: The A1 notation of the range to retrieve.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueRange"
        "400":
          description: Bad Request

  /{spreadsheetId}/values/{range}:append:
    post:
      summary: Append values to a spreadsheet
      operationId: appendSpreadsheetValues
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier for the spreadsheet.
        - name: range
          in: path
          required: true
          schema:
            type: string
          description: The A1 notation of the range to search for a table.
        - name: valueInputOption
          in: query
          required: true
          schema:
            type: string
            enum:
              - RAW
              - USER_ENTERED
          description: How the input data should be interpreted.
        - name: insertDataOption
          in: query
          schema:
            type: string
            enum:
              - OVERWRITE
              - INSERT_ROWS
          description: How the input data should be inserted.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValueRange"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppendValuesResponse"
        "400":
          description: Bad Request

components:
  schemas:
    ValueRange:
      type: object
      properties:
        values:
          type: array
          items:
            type: array
            items:
              type: string
          description: The new data to be placed in the range.
    AppendValuesResponse:
      type: object
      properties:
        spreadsheetId:
          type: string
        tableRange:
          type: string
        updates:
          type: object
          properties:
            updatedRange:
              type: string
            updatedRows:
              type: integer
            updatedColumns:
              type: integer
            updatedCells:
              type: integer
